In [3]:
import pandas as pd
import numpy as np 

In [4]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [10]:
#creating a new column called spam which has a binary represntation of spam of ham 
df['spam'] = df.Category.apply(lambda x: 1 if x=="spam" else 0 )

In [11]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [16]:
X_train.shape, X_test.shape

((4457,), (1115,))

In [17]:
type(X_train)

pandas.core.series.Series

In [21]:
X_train[:4]

2801    House-Maid is the murderer, coz the man was mu...
1365    Hey i will be really pretty late... You want t...
2161    No. Its not specialisation. Can work but its s...
1827    Dude. What's up. How Teresa. Hope you have bee...
Name: Message, dtype: object

In [22]:
type(y_train)

pandas.core.series.Series

In [23]:
y_train[:4]

2801    0
1365    0
2161    0
1827    0
Name: spam, dtype: int64

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7820 sparse matrix of type '<class 'numpy.int64'>'
	with 59543 stored elements in Compressed Sparse Row format>

In [26]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [27]:
X_train_cv.shape

(4457, 7820)

In [30]:
v.get_feature_names_out()[1000:1050]

array(['answering', 'answers', 'answr', 'antha', 'anthony', 'anti', 'any',
       'anybody', 'anyhow', 'anymore', 'anyone', 'anyones', 'anyplaces',
       'anythiing', 'anythin', 'anything', 'anythingtomorrow', 'anytime',
       'anyway', 'anyways', 'anywhere', 'aom', 'apart', 'apartment',
       'apes', 'apeshit', 'aphex', 'apnt', 'apo', 'apologetic',
       'apologise', 'apologize', 'app', 'apparently', 'appeal', 'appear',
       'appendix', 'applausestore', 'applebees', 'apples', 'application',
       'apply', 'applyed', 'applying', 'appointment', 'appointments',
       'appreciate', 'appreciated', 'approaches', 'appropriate'],
      dtype=object)

In [31]:
v.get_feature_names_out().shape

(7820,)

In [32]:
X_train_np = X_train_cv.toarray()
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [33]:
np.where(X_train_np[0]!=0)

(array([ 932, 1064, 1099, 1883, 2074, 3247, 3297, 3512, 3560, 3695, 3744,
        3796, 3842, 4302, 4366, 4384, 4706, 4707, 4966, 4995, 5394, 5555,
        6869, 6885, 7457]),)

In [38]:
X_train_np[0][932]

1

In [42]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [43]:
X_test_cv = v.transform(X_test)

In [44]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       971
           1       0.95      0.92      0.94       144

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [46]:
emails = [ 
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusivce offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [48]:
#Now what ever we have done we are giong to do in the sklearn pipeline :

from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])


In [49]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [50]:
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       971
           1       0.95      0.92      0.94       144

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115

